name: deploy

on:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      
      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      # Install wix: https://wixtoolset.org/docs/intro/
      - name: Install wix tool
        run: dotnet tool install --global wix

      # Build project: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-build
      - name: Build
        run: dotnet build -c Release
      
      # Get msi version
      - name: Get msi version
        id: current-date
        uses: juliangruber/read-file-action@v1
        with:
          path: bin/msi_version.txt
      
      # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Bim4Everyone
          path: bin/Bim4Everyone_${{ steps.current-date.outputs.content }}.msi
      
      # Publish release: https://github.com/softprops/action-gh-release
      - name: Publish Release (Release)
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.current-date.outputs.content }}
          name: Bim4Everyone v${{ steps.current-date.outputs.content }}
          body: Publish Release
          draft: true
          prerelease: false
          files: |
            bin/Bim4Everyone_${{ steps.current-date.outputs.content }}.msi