name: notification

env:
  body_message: |
    🚀 Bim4Everyone
    ⬇️ Платформа обновлена: [скачать](${{ github.event.release.html_url }})

on:
  # when release published
  release:
    types: [ published ]

jobs:
  telegram:
    runs-on: ubuntu-latest
    steps:
      # Telegram Notify: https://github.com/appleboy/telegram-action/
      - name: Telegram Notify
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: ${{ env.body_message }}

  vk-teams:
    runs-on: ubuntu-latest
    steps:
      # VK Teams Notify: https://github.com/dosymep/vk-teams-action/
      - name: VK Teams Notify
        uses: dosymep/vk-teams-action@v1.0.0
        with:
          to: ${{ secrets.VK_TEAMS_TO }}
          token: ${{ secrets.VK_TEAMS_TOKEN }}
          api_url: ${{ secrets.VK_TEAMS_API_URL }}
          format: MarkdownV2
          message: ${{ env.body_message }}
          